version: '3.8'

services:
  drizzle-pg-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: drizzle-edge-pg-proxy-client:bun
    container_name: drizzle-pg-proxy
    environment:
      - NODE_ENV=production
      # Database connection - this should be set in Coolify
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_TOKEN=${AUTH_TOKEN:-}
      - PORT=${CONTAINER_PORT:-8080}
      # Performance tuning
      - NODE_OPTIONS=--max-old-space-size=2048
      # Database connection pool
      - DB_POOL_MIN=5
      - DB_POOL_MAX=20
      - DB_POOL_IDLE_TIMEOUT=10000
      # Enable response compression
      - ENABLE_COMPRESSION=true
    ports:
      - "${HTTP_PORT:-7432}:${CONTAINER_PORT:-8080}"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${CONTAINER_PORT:-8080}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped